<a href="https://colab.research.google.com/github/shirish-baral/deep-learning/blob/main/pytorch_nn_torch_optim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Changes to be done  -  Not Manually required:**

nn module will create neurons and modules

use built-in loss function

use built-in activation function

update parameteres using built-in optimizer



In [42]:
# create model class
# 5 input -> one activation function -> one output

import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1) #single neuron - 5 input, 1 output
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [43]:
#create dataset
features = torch.rand(10,5) # 5 columns because 5 features

#create model
model = Model(features.shape[1]) # create model object with 5 features

# call model for froward pass
model(features) #forward method is triggered when model is called


tensor([[0.4545],
        [0.4576],
        [0.4449],
        [0.4290],
        [0.5402],
        [0.4392],
        [0.4712],
        [0.4923],
        [0.4389],
        [0.4395]], grad_fn=<SigmoidBackward0>)

In [44]:
#show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.0451, -0.4285, -0.0603,  0.2698,  0.3139]], requires_grad=True)

In [45]:
model.linear.bias

Parameter containing:
tensor([-0.2273], requires_grad=True)

In [46]:
!pip install torchinfo

In [47]:
from torchinfo import summary

In [48]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# **Input -> Hidden -> Ouput**

Input Layer (5) -> Hidden_1 (3) -> Output (1) -> y_pred

              ReLU             Sigmoid

5x3 + 3x1 = 18 weights, 3x1 + 1 = 4 biases

In [71]:
# create model class

import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )
  def forward(self, features):
    out = self.network(features)
    return out

In [66]:
#create dataset
features = torch.rand(10,5) # 5 columns because 5 features

#create model
model = Model(features.shape[1]) # create model object with 5 features

# call model for froward pass
model(features) #forward method is triggered when model is called


tensor([[0.4767],
        [0.4444],
        [0.4762],
        [0.4510],
        [0.4809],
        [0.4449],
        [0.4634],
        [0.4353],
        [0.5271],
        [0.4847]], grad_fn=<SigmoidBackward0>)

In [67]:
# weight of input-hidden layer
model.linear1.weight

Parameter containing:
tensor([[-0.1067,  0.3023,  0.0916,  0.3763,  0.3080],
        [-0.3262,  0.1168,  0.0091,  0.3860, -0.3537],
        [-0.0068,  0.2425, -0.4054,  0.3668,  0.2942]], requires_grad=True)

In [68]:
# weight of hidden-output layer
print(model.linear2.weight)
print(f'Biases {model.linear2.bias}')

Parameter containing:
tensor([[0.4720, 0.1836, 0.2916]], requires_grad=True)
Biases Parameter containing:
tensor([-0.2652], requires_grad=True)


In [69]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00