<a href="https://colab.research.google.com/github/shirish-baral/deep-learning/blob/main/PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

In [4]:
print(torch.__version__)

2.6.0+cu124


In [5]:
if torch.cuda.is_available():
    print("CUDA is available.")
    print("Number of CUDA devices:", torch.cuda.device_count())
    print("Device name:", torch.cuda.get_device_name(0))
else:
    print("CUDA is not available.")

CUDA is available.
Number of CUDA devices: 1
Device name: Tesla T4


**Creating a Tensor**

In [6]:
# using empty
a = torch.empty(2,3)
type(a)

torch.Tensor

In [7]:
# check type
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# using rand
torch.rand(2,3)

tensor([[0.8638, 0.6864, 0.0728],
        [0.7294, 0.1865, 0.9052]])

In [10]:
# use of seed
# manual seed is used to retain random values
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
# arrange -- values within a range as per steps
print("using arange ->", torch.arange(0,10,2))

using arange -> tensor([0, 2, 4, 6, 8])


In [13]:
# using linspace -- evenly spaced values between 0 to 10
print("using linspace ->",torch.linspace(0,10,10))

using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [14]:
 # using eye --- identity matrix
 print("using eye ->",torch.eye(3))

using eye -> tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [15]:
# using full -- all items same
print("using full ->",torch.full((2,3),7))

using full -> tensor([[7, 7, 7],
        [7, 7, 7]])


# **Tensor Shapes**

In [16]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
x.shape

torch.Size([2, 3])

In [18]:
torch.empty_like(x) #tensor with same shape as x

tensor([[              0,      1165788448,      1139385840],
        [135216630049648,               0,               0]])

In [19]:
torch.zeros_like(x) #tensor with same shape as x but all values 0

tensor([[0, 0, 0],
        [0, 0, 0]])

# Tensor Data Types

In [20]:
# find data type
x.dtype

torch.int64

In [21]:
# assign data type
torch.tensor([4.0,5.0,6.0], dtype=torch.int32)

tensor([4, 5, 6], dtype=torch.int32)

In [22]:
torch.tensor([1.0,2.0,3.0], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [23]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# **Mathematical Operations**

1. Scalar Operation

In [24]:
x = torch.rand(2,2)
x

tensor([[0.2627, 0.0428],
        [0.2080, 0.1180]])

In [25]:
# addition
x + 2

#subscription
x - 2

# multiplication
x * 3

# division
x/3

# mod
((x * 100)//3)%2


tensor([[0., 1.],
        [0., 1.]])

2. Element wise operation

In [26]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.1217, 0.7356, 0.7118],
        [0.7876, 0.4183, 0.9014]])
tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])


In [27]:
# add
a + b
# sub
a - b
# multiply
a * b

tensor([[0.1213, 0.5565, 0.1594],
        [0.2381, 0.0746, 0.7426]])

In [28]:
# abs
s = torch.tensor([-1,2,-3,4])
torch.abs(s)

tensor([1, 2, 3, 4])

round, neg, ceil, floor can also be performed

In [29]:
# clamp -- all numbers in a range
torch.clamp(s, min=2, max =3)

tensor([2, 2, 2, 3])

# **3. Reduction Operation**

In [30]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[4., 6., 0.],
        [1., 9., 9.]])

In [31]:
# sum
torch.sum(e)

tensor(29.)

In [32]:
# sum of columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([10., 19.])

In [33]:
# mean
torch.mean(e)

tensor(4.8333)

Similarly, product(prod), std, var, max, min can be computed

# 4. Matrix **Operations**

In [34]:
f = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
g = torch.randint(size=(3,2), low=0, high=10, dtype=torch.float32)
print(f)
print(g)

tensor([[8., 0., 7.],
        [0., 0., 9.]])
tensor([[5., 7.],
        [3., 9.],
        [4., 0.]])


In [35]:
# matrix multiplication
torch.matmul(f, g)

tensor([[68., 56.],
        [36.,  0.]])

In [36]:
vector1 = torch.tensor([1,2,3])
vector2 = torch.tensor([4,5,6])

# dot product
torch.dot(vector1, vector2)

tensor(32)

In [37]:
# transpose
torch.transpose(f, 0, 1)

tensor([[8., 0.],
        [0., 0.],
        [7., 9.]])

In [38]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 7., 5.],
        [9., 9., 7.],
        [5., 9., 8.]])

In [39]:
# determinant
torch.det(h)

tensor(-34.0000)

In [40]:
torch.inverse(h)

tensor([[-0.2647,  0.3235, -0.1176],
        [ 1.0882, -0.4412, -0.2941],
        [-1.0588,  0.2941,  0.5294]])

# **5. Comparison Operations**

In [41]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)
print(i)
print(j)

tensor([[9, 7, 9],
        [2, 6, 7]])
tensor([[7, 8, 3],
        [6, 1, 5]])


In [42]:
# greater than
i > j
# less than
i<j
# equal to
i == j

tensor([[False, False, False],
        [False, False, False]])

# **6. Special Functions**

In [43]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[5., 0., 4.],
        [3., 8., 8.]])

In [44]:
# log
torch.log(k)

tensor([[1.6094,   -inf, 1.3863],
        [1.0986, 2.0794, 2.0794]])

In [45]:
# exp
torch.exp(k)

tensor([[1.4841e+02, 1.0000e+00, 5.4598e+01],
        [2.0086e+01, 2.9810e+03, 2.9810e+03]])

In [46]:
# sigmoid function
torch.sigmoid(k)

tensor([[0.9933, 0.5000, 0.9820],
        [0.9526, 0.9997, 0.9997]])

In [47]:
# relu
torch.relu(k)

tensor([[5., 0., 4.],
        [3., 8., 8.]])

--------------

# Inpace Operations
--> store output in same tensor instead of creating another

In [48]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.6179, 0.3379, 0.2170],
        [0.9454, 0.7116, 0.1157]])
tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])


In [49]:
m.add_(n) # result stored in m

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])

In [50]:
m

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])

In [51]:
n

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [52]:
m.relu_() # relu applied and stored in m

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])

# Copying Tensor

In [53]:
a = torch.rand(2,3)
a

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [54]:
b = a.clone()

In [55]:
b

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [56]:
a[0][0]=15
a

tensor([[1.5000e+01, 7.4799e-02, 9.6049e-01],
        [3.2709e-01, 1.0255e-02, 9.5160e-01]])

In [57]:
b #changes in 'a' did not affect b

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

_________________________________

### **Tensor Operations on GPU**

In [58]:
torch.cuda.is_available()

True

In [59]:
device = torch.device('cuda')

In [60]:
# creating a new tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [61]:
# moving an existing tensor to GPU
a = torch.rand((2,3))
a.to(device)

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]], device='cuda:0')

In [62]:
b = a.to(device)

In [63]:
b + 5

tensor([[5.2855, 5.2324, 5.9141],
        [5.7668, 5.1659, 5.4393]], device='cuda:0')

# Reshaping Tensprs

In [64]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [65]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [66]:
# flatten -- to single dimension
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [67]:
b = torch.rand(2,3,4) # 2rows, 3 inner rows, 4 columns
b

tensor([[[0.2243, 0.8935, 0.0497, 0.1780],
         [0.3011, 0.1893, 0.9186, 0.2131],
         [0.3957, 0.6017, 0.4234, 0.5224]],

        [[0.4175, 0.0340, 0.9157, 0.3079],
         [0.6269, 0.8277, 0.6594, 0.0887],
         [0.4890, 0.5887, 0.7340, 0.8497]]])

In [68]:
# permute
b.permute(2,0,1) # shape now (4,2,3)

tensor([[[0.2243, 0.3011, 0.3957],
         [0.4175, 0.6269, 0.4890]],

        [[0.8935, 0.1893, 0.6017],
         [0.0340, 0.8277, 0.5887]],

        [[0.0497, 0.9186, 0.4234],
         [0.9157, 0.6594, 0.7340]],

        [[0.1780, 0.2131, 0.5224],
         [0.3079, 0.0887, 0.8497]]])

In [69]:
# unsqueeze
c = torch.rand(226,226,3)
c.unsqueeze(dim=0).shape # shape now (1,226,226,3)

torch.Size([1, 226, 226, 3])

In [70]:
# squeeze
d = torch.rand(1,20)
d.squeeze(dim=0).shape # shape now (20,)

torch.Size([20])

# NumPy and PyTorch

In [71]:
import numpy as np

In [72]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [73]:
b = a.numpy()

In [74]:
type(b)

numpy.ndarray

In [75]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [76]:
torch.from_numpy(c)

tensor([1, 2, 3])